[package]
name = "json_example"
version = "0.1.1"
authors = ["Mike Tang <miketang84@outlook.com>"]

[dependencies]
sapper = "0.2"
sapper_std = "0.2"
log = "*"
env_logger = "*"
serde="*"
serde_json="*"
serde_derive="*"
